// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghklfwmpswfhsfhkkmcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdoa2xmd21wc3dmaHNmaGtrbWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDA4MjcsImV4cCI6MjA2Njk3NjgyN30.Qg3bSPRdaef4NA7eGdg4URTq17PRBPa1-kFzd-N1Pr0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});